#kubectl expose deployment nginx01 --type=ClusterIP --name=nginx01
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx01
  name: nginx01
  namespace: default
spec:
  clusterIP: 10.103.230.133
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx01
  type: ClusterIP
status:
  loadBalancer: {}