#kubectl expose deployment nginx01 --type=LoadBalancer --name=nginx01
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx01
  name: nginx01
  namespace: default
spec:
  clusterIP: 10.110.90.192
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32370
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx01
  type: LoadBalancer
status:
  loadBalancer: {}